'use strict';
const express = require('express');
const auth = require('../controllers/authController');
const core = require('../controllers/coreController');
const identity = require('../controllers/identityController');
const domain = require('../controllers/domainController');
const workflow = require('../controllers/workflowController');
const moderation = require('../controllers/moderationController');
const ai = require('../controllers/aiController');
const uploads = require('../controllers/uploadController');
const { authenticate, optionalAuth, rolesRequired } = require('../middleware/auth');
const router = express.Router();
const admin = rolesRequired('admin');
const employer = rolesRequired('employer');
router.post('/auth/register', auth.register);
router.post('/auth/login', auth.login);
router.get('/auth/me', authenticate, auth.me);
router.get('/stats', core.stats);
router.get('/users', ...admin, core.users);
router.get('/users/me/skills', authenticate, core.listUserSkills);
router.post('/users/me/skills', authenticate, core.createUserSkill);
router.put('/users/me/skills/:id', authenticate, core.updateUserSkill);
router.delete('/users/me/skills/:id', authenticate, core.deleteUserSkill);
router.post('/users/me/nic-document', authenticate, core.deprecatedIdentity);
router.post('/users/me/identity-verification', authenticate, core.deprecatedIdentity);
router.post('/users/me/identity-verification/phone/send', authenticate, identity.sendPhoneOtp);
router.post('/users/me/identity-verification/phone/confirm', authenticate, identity.confirmPhoneOtp);
router.post('/users/me/identity-verification/email/send', authenticate, identity.sendEmailOtp);
router.post('/users/me/identity-verification/email/confirm', authenticate, identity.confirmEmailOtp);
router.put('/users/:id/identity-verification/review', ...admin, core.deprecatedIdentity);
router.get('/users/:id', authenticate, core.getUser);
router.put('/users/:id', authenticate, core.updateUser);
router.delete('/users/:id', authenticate, core.deleteUser);
router.post('/users/:id/avatar', authenticate, uploads.avatar);
router.delete('/users/:id/avatar', authenticate, uploads.deleteAvatar);
router.get('/skills', core.listSkills);
router.post('/skills', ...admin, core.createSkill);
router.get('/skills/:id', core.getSkill);
router.put('/skills/:id', ...admin, core.updateSkill);
router.delete('/skills/:id', ...admin, core.deleteSkill);
router.get('/user-skills', ...employer, core.listUserSkills);
router.post('/user-skills', ...employer, core.createUserSkill);
router.get('/user-skills/:id', ...employer, core.getUserSkill);
router.put('/user-skills/:id', ...employer, core.updateUserSkill);
router.delete('/user-skills/:id', ...employer, core.deleteUserSkill);
router.get('/user-skills/:id/work-samples', ...employer, core.samples);
router.post('/user-skills/:id/work-samples', ...employer, core.createSample);
router.post('/work-samples/:id/verify', ...employer, core.verifySample);
router.get('/categories', optionalAuth, async (req, _res, next) => {
  if (!req.jwt) return next();
  const { User } = require('../models');
  req.user = await User.findOne({ id: Number(req.jwt.sub) });
  next();
}, core.listCategories);
router.post('/categories', ...admin, core.createCategory);
router.post('/categories/request', authenticate, core.requestCategory);
router.get('/categories/:id', core.getCategory);
router.put('/categories/:id', ...admin, core.updateCategory);
router.post('/categories/:id/approve', ...admin, core.reviewCategory);
router.post('/categories/:id/reject', ...admin, core.reviewCategory);
router.delete('/categories/:id', ...admin, core.deleteCategory);
router.get('/categories/:id/pricing-suggestion', core.categoryPricing);
router.post('/categories/:id/seed-pricing', ...admin, core.seedPricing);
router.post('/categories/:id/seed-district-pricing', ...admin, core.seedDistrictPricing);
router.post('/categories/seed-district-pricing', ...admin, core.seedDistrictPricing);
router.post('/categories/:id/recalc-pricing', ...admin, core.categoryPricing);
router.get('/jobs/suggested-price', ...rolesRequired('user'), core.suggestedPrice);

router.get('/ai/concierge', authenticate, ai.meta);
router.post('/ai/concierge', authenticate, ai.concierge);
router.get('/communities', optionalAuth, domain.communities.list);
router.post('/communities', ...employer, domain.communities.create);
router.get('/communities/:id', optionalAuth, domain.communities.get);
router.put('/communities/:id', ...employer, domain.communities.update);
router.patch('/communities/:id', ...employer, domain.communities.update);
router.patch('/communities/:id/verify', ...admin, domain.communities.verify);
router.put('/communities/:id/review', ...admin, domain.communities.verify);
router.delete('/communities/:id', ...employer, domain.communities.remove);
router.post('/communities/:id/image', ...employer, uploads.community);
router.get('/communities/:id/recommended-jobs', ...employer, ai.recommendedJobs);
router.get('/communities/:id/review-digest', domain.communities.digest);
router.post('/communities/:id/join-requests/:user_id/fit-analysis', ...employer, ai.fit);
router.get('/community-members/my', ...employer, domain.members.mine);
router.post('/community-members/join/:community_id', ...employer, domain.members.join);
router.get('/community-members/community/:community_id', ...employer, domain.members.list);
router.post('/community-members/:id/approve', ...employer, domain.members.decide);
router.post('/community-members/:id/reject', ...employer, domain.members.decide);
router.delete('/community-members/:id', ...employer, domain.members.remove);
router.get('/jobs', authenticate, domain.jobs.list);
router.post('/jobs', ...rolesRequired('user'), domain.jobs.create);
router.post('/jobs/generate-description', ...rolesRequired('user'), ai.jobDescription);
router.get('/jobs/:id', authenticate, domain.jobs.get);
router.put('/jobs/:id', ...rolesRequired('user'), domain.jobs.update);
router.delete('/jobs/:id', ...rolesRequired('user'), domain.jobs.remove);
router.get('/jobs/:id/applications', ...rolesRequired('user'), domain.jobs.applications);
router.get('/jobs/:id/recommended-communities', ...rolesRequired('user'), ai.recommendedCommunities);
router.post('/jobs/:id/suggest-bid', ...employer, ai.suggestBid);
router.post('/jobs/:id/invite', ...rolesRequired('user'), domain.communityApplications.invite);
router.get('/community-applications/my', ...employer, domain.communityApplications.mine);
router.post('/community-applications/apply', ...employer, domain.communityApplications.apply);
router.get('/community-applications/job/:job_id', ...rolesRequired('user'), domain.communityApplications.forJob);
router.post('/community-applications/:id/approve', ...rolesRequired('user'), domain.communityApplications.decide);
router.post('/community-applications/:id/reject', ...rolesRequired('user'), domain.communityApplications.decide);
router.get('/contracts', authenticate, workflow.contracts.list);
router.get('/contracts/needs-attention', authenticate, workflow.contracts.attention);
router.get('/contracts/:id', authenticate, workflow.contracts.get);
router.post('/contracts/:id/open-internally', authenticate, workflow.contracts.open);
router.post('/contracts/:id/select-member', authenticate, workflow.contracts.select);
router.post('/contracts/:id/select-members', authenticate, workflow.contracts.selectMany);
router.post('/contracts/:id/submit-deliverable', authenticate, workflow.contracts.submit);
router.post('/contracts/:id/admin-approve-deliverable', authenticate, workflow.contracts.adminApprove);
router.post('/contracts/:id/poster-approve-deliverable', authenticate, workflow.contracts.posterApprove);
router.post('/contracts/:id/client-approve-deliverable', authenticate, workflow.contracts.posterApprove);
router.post('/contracts/:id/ai-review-deliverable', authenticate, ai.deliverable);
router.get('/contracts/:id/messages', authenticate, workflow.messages.list);
router.post('/contracts/:id/messages', authenticate, workflow.messages.send);
router.post('/contracts/:id/messages/suggest-reply', authenticate, workflow.messages.suggest);
router.delete('/messages/:id/delete-for-me', authenticate, workflow.messages.deleteMine);
router.delete('/messages/:id/delete-for-everyone', authenticate, workflow.messages.deleteAll);
router.get('/contract-applications/my', authenticate, workflow.contractApplications.mine);
router.post('/contract-applications/apply', authenticate, workflow.contractApplications.apply);
router.get('/contract-applications/contract/:contract_id', authenticate, workflow.contractApplications.list);
router.get('/notifications', authenticate, workflow.notifications.list);
router.get('/notifications/unread-count', authenticate, workflow.notifications.count);
router.patch('/notifications/:id/read', authenticate, workflow.notifications.read);
router.put('/notifications/:id/read', authenticate, workflow.notifications.read);
router.patch('/notifications/read-all', authenticate, workflow.notifications.all);
router.put('/notifications/read-all', authenticate, workflow.notifications.all);
router.get('/open-calls', workflow.openCalls.list);
router.post('/open-calls', authenticate, workflow.openCalls.create);
router.post('/open-calls/generate-description', authenticate, ai.openCallDescription);
router.get('/open-calls/:id', workflow.openCalls.get);
router.put('/open-calls/:id', authenticate, workflow.openCalls.update);
router.delete('/open-calls/:id', authenticate, workflow.openCalls.remove);
router.get('/payments/my-earnings', authenticate, moderation.payments.list);
router.get('/payments', authenticate, moderation.payments.list);
router.get('/reviews', moderation.reviews.list);
router.post('/reviews', ...rolesRequired('user'), moderation.reviews.create);
router.get('/reports', ...admin, moderation.reports.list);
router.post('/reports', authenticate, moderation.reports.create);
router.get('/reports/mine', authenticate, moderation.reports.mine);
router.get('/reports/:id', ...admin, moderation.reports.get);
router.get('/reports/:id/ai-summary', ...admin, ai.report);
router.patch('/reports/:id', ...admin, moderation.reports.update);
module.exports = router;
