'use strict';
const { User, Community, CommunityMember, Job, Contract, Report, Review }=require('../models');
const { wrap, communityJson, jobJson }=require('./domainController');
const { isCommunityAdmin }=require('./coreController');
const { askAi,parseObject }=require('../services/aiService');
const unavailable=(res,key='suggestion')=>res.status(503).json({error:'AI suggestion unavailable.',[key]:null});
const ai={
 meta:(_req,res)=>res.json({available:Boolean(process.env.OPENROUTER_API_KEY)}),
 concierge:wrap(async(req,res)=>{const q=String(req.body.question||'').trim();if(!q)return res.status(400).json({error:'question is required.'});if(q.length>500)return res.status(400).json({error:'question is too long (max 500 chars).'});const answer=await askAi('You are HireHub Community Concierge. Answer concisely using only the supplied user context.',`User: ${req.user.full_name} (${req.user.role})\nQuestion: ${q}`);if(!answer)return unavailable(res,'answer');res.json({answer,available:true});}),
 jobDescription:wrap(async(req,res)=>{const prompt=String(req.body.prompt||'').trim();if(!prompt)return res.status(400).json({error:'prompt is required.'});if(prompt.length>1000)return res.status(400).json({error:'prompt is too long (max 1000 chars).'});const text=await askAi('Return JSON only with title, description, and category.',prompt,700),suggestion=parseObject(text);return suggestion?res.json({suggestion,assistive:true}):unavailable(res);}),
 openCallDescription:wrap(async(req,res)=>{const prompt=String(req.body.prompt||req.body.title||'').trim();if(!prompt)return res.status(400).json({error:'title or prompt is required.',suggestion:null});const text=await askAi('Write a concise recruiting open-call description.',prompt);return text?res.json({suggestion:{description:text},assistive:true}):unavailable(res);}),
 deliverable:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(!c.deliverable_url&&!c.deliverable_notes)return res.status(400).json({error:'No deliverable submitted yet.'});const text=await askAi('Review this deliverable assistively. Return JSON with verdict, summary, concerns.',JSON.stringify({url:c.deliverable_url,notes:c.deliverable_notes})),review=parseObject(text);return review?res.json({review,assistive:true}):unavailable(res,'review');}),
 report:wrap(async(req,res)=>{const r=await Report.findOne({id:Number(req.params.id)});if(!r)return res.status(404).json({error:'Report not found.',summary:null});const text=await askAi('Summarize this moderation dispute neutrally for an administrator.',JSON.stringify(r.toObject()));return text?res.json({summary:text,assistive:true}):unavailable(res,'summary');}),
 recommendedCommunities:wrap(async(req,res)=>{const j=await Job.findOne({id:Number(req.params.id)});if(!j)return res.status(404).json({error:'Job not found.'});if(j.posted_by_id!==req.userId)return res.status(403).json({error:'Only the job poster can view recommended communities.'});const rows=await Community.find({status:'approved',category_id:j.category_id});res.json({recommendations:await Promise.all(rows.map(async(c,i)=>({community:await communityJson(c,true),score:Math.max(0,100-i),ai_blurb:null})))});}),
 recommendedJobs:wrap(async(req,res)=>{const c=await Community.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Community not found.'});if(!await isCommunityAdmin(req.userId,c.id))return res.status(403).json({error:'Community admin access required.'});const rows=await Job.find({status:'open',category_id:c.category_id});res.json({recommendations:await Promise.all(rows.map(async(j,i)=>({job:await jobJson(j,true),score:Math.max(0,100-i),ai_blurb:null})))});}),
 suggestBid:wrap(async(req,res)=>{const j=await Job.findOne({id:Number(req.params.id)});if(!j)return res.status(404).json({error:'Job not found.'});if(!req.body.community_id)return res.status(400).json({error:'community_id is required.'});if(!await isCommunityAdmin(req.userId,req.body.community_id))return res.status(403).json({error:'Community admin access required.'});const text=await askAi('Return JSON only: bid_amount, rationale, estimated_days.',JSON.stringify(j.toObject())),suggestion=parseObject(text);return suggestion?res.json({suggestion,assistive:true}):unavailable(res);}),
 fit:wrap(async(req,res)=>{const c=await Community.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({available:false,error:'Community not found.'});if(!await isCommunityAdmin(req.userId,c.id))return res.status(403).json({available:false,error:'Community admin access required.'});const member=await CommunityMember.findOne({community_id:c.id,user_id:Number(req.params.user_id),status:'pending'});if(!member)return res.status(404).json({available:false,error:'Pending join request not found.'});const u=await User.findOne({id:member.user_id});const text=await askAi('Assess applicant fit. Return concise JSON.',JSON.stringify({community:c,applicant:u})),analysis=parseObject(text);return analysis?res.json({available:true,analysis}):res.status(503).json({available:false,error:'AI analysis unavailable.'});}),
};
module.exports=ai;
