'use strict';
const passwordUtil = require('../utils/password');
const {
  User, Skill, UserSkill, WorkSample, Category, PricingReference, Community, CommunityMember,
  Job, CommunityApplication, Contract, ContractApplication, Conversation, Message, Notification,
  OpenCall, OpenCallSkill, Payment, Review, Report, AiReviewDigest, publicDoc,
} = require('../models');
const { serializeUser } = require('./authController');
const clean = publicDoc;
const byId = (Model, req) => Model.findOne({ id: Number(req.params.id) });
const titleCase = v => String(v || '').trim().replace(/\b\w/g, c => c.toUpperCase());
async function skillLink(link, samples = false) { const out = clean(link); out.skill = clean(await Skill.findOne({ id: link.skill_id })); const ws = await WorkSample.find({ user_skill_id: link.id }).sort({ created_at: -1 }); out.ai_reviewed = ws.some(x => x.verification_status === 'plausible'); if (samples) out.work_samples = ws.map(clean); return out; }
async function isCommunityAdmin(userId, communityId) { const c = await Community.findOne({ id: Number(communityId) }); return Boolean(c && (c.admin_id === userId || await CommunityMember.exists({ community_id: c.id, user_id: userId, role: 'admin', status: 'approved' }))); }

const stats = async (_req, res) => res.json({ users: await User.countDocuments(), communities: await Community.countDocuments({ status: 'approved' }), jobs: await Job.countDocuments(), completed_contracts: await Contract.countDocuments({ status: 'completed' }) });
async function users(req, res) { res.json({ users: await Promise.all((await User.find()).map(u => serializeUser(u))) }); }
async function getUser(req, res) { const u = await byId(User, req); if (!u) return res.status(404).json({ error: 'User not found.' }); res.json({ user: await serializeUser(u, { self: req.userId === u.id, stats: true, skills: true }) }); }
async function updateUser(req, res) { const u = await byId(User, req); if (!u) return res.status(404).json({ error: 'User not found.' }); if (req.userId !== u.id && req.user.role !== 'admin') return res.status(403).json({ error: 'Forbidden.' }); const allowed = ['full_name','bio','location','phone_number','address_line1','address_line2','address_city','address_region','address_postal_code']; for (const k of allowed) if (k in req.body) u[k] = req.body[k]; if (req.body.password) u.password = await passwordUtil.hash(req.body.password); await u.save(); res.json({ message: 'User updated.', user: await serializeUser(u, { self: req.userId === u.id, skills: true }) }); }
async function deleteUser(req, res) { const u = await byId(User, req); if (!u) return res.status(404).json({ error: 'User not found.' }); if (req.userId !== u.id && req.user.role !== 'admin') return res.status(403).json({ error: 'Forbidden.' }); await u.deleteOne(); res.json({ message: 'User deleted.' }); }
const deprecatedIdentity = (_req, res) => res.status(410).json({ error: 'NIC identity verification has been removed. Use phone or email verification.' });
const otpUnavailable = (_req, res) => res.status(503).json({ error: 'OTP delivery is not configured.' });

async function listSkills(_req, res) { res.json({ skills: (await Skill.find().sort({ name: 1 })).map(clean) }); }
async function createSkill(req, res) { if (!req.body.name) return res.status(400).json({ errors: ['name is required.'] }); try { const x = await Skill.create({ name: req.body.name, category: req.body.category }); res.status(201).json({ message: 'Skill created.', skill: clean(x) }); } catch (e) { if (e.code === 11000) return res.status(409).json({ error: 'Skill already exists.' }); throw e; } }
async function getSkill(req, res) { const x = await byId(Skill, req); return x ? res.json({ skill: clean(x) }) : res.status(404).json({ error: 'Skill not found.' }); }
async function updateSkill(req, res) { const x = await byId(Skill, req); if (!x) return res.status(404).json({ error: 'Skill not found.' }); for (const k of ['name','category']) if (k in req.body) x[k] = req.body[k]; await x.save(); res.json({ message: 'Skill updated.', skill: clean(x) }); }
async function deleteSkill(req, res) { const x = await byId(Skill, req); if (!x) return res.status(404).json({ error: 'Skill not found.' }); await x.deleteOne(); res.json({ message: 'Skill deleted.' }); }
async function listUserSkills(req, res) { const userId = req.path.startsWith('/me/') ? req.userId : Number(req.query.user_id || req.userId); res.json({ user_skills: await Promise.all((await UserSkill.find({ user_id: userId })).map(x => skillLink(x))) }); }
async function createUserSkill(req, res) { const data = { ...req.body, user_id: req.path.startsWith('/me/') ? req.userId : Number(req.body.user_id || req.userId) }; const errors=[]; if (!data.user_id) errors.push('user_id is required.'); if (!data.skill_id) errors.push('skill_id is required.'); if (errors.length) return res.status(400).json({ errors }); try { const x=await UserSkill.create(data); res.status(201).json({ message:'User skill created.', user_skill:await skillLink(x) }); } catch(e){ if(e.code===11000)return res.status(409).json({error:'User already has this skill.'}); throw e;} }
async function getUserSkill(req,res){const x=await byId(UserSkill,req); return x?res.json({user_skill:await skillLink(x)}):res.status(404).json({error:'User skill not found.'});}
async function updateUserSkill(req,res){const x=await byId(UserSkill,req);if(!x)return res.status(404).json({error:'User skill not found.'});if(req.path.startsWith('/me/')&&x.user_id!==req.userId)return res.status(403).json({error:'Unauthorized to update this skill.'});if('level'in req.body)x.level=req.body.level;await x.save();res.json({message:'User skill updated.',user_skill:await skillLink(x)});}
async function deleteUserSkill(req,res){const x=await byId(UserSkill,req);if(!x)return res.status(404).json({error:'User skill not found.'});if(req.path.startsWith('/me/')&&x.user_id!==req.userId)return res.status(403).json({error:'Unauthorized to delete this skill.'});await WorkSample.deleteMany({user_skill_id:x.id});await x.deleteOne();res.json({message:'User skill deleted.'});}
async function samples(req,res){const x=await UserSkill.findOne({id:Number(req.params.id)});if(!x)return res.status(404).json({error:'User skill not found.'});if(x.user_id!==req.userId)return res.status(403).json({error:'Forbidden.'});res.json({user_skill:await skillLink(x,true)});}
async function createSample(req,res){const x=await UserSkill.findOne({id:Number(req.params.id)});if(!x)return res.status(404).json({error:'User skill not found.'});if(x.user_id!==req.userId)return res.status(403).json({error:'Forbidden.'});const type=req.body.sample_type;if(!['text','image'].includes(type))return res.status(400).json({errors:['sample_type must be text or image.']});if(!req.body.content)return res.status(400).json({errors:['content is required.']});const s=await WorkSample.create({user_skill_id:x.id,sample_type:type,content:req.body.content});res.status(201).json({message:'Work sample created.',work_sample:clean(s)});}
async function verifySample(req,res){const s=await byId(WorkSample,req);if(!s)return res.status(404).json({error:'Work sample not found.'});const x=await UserSkill.findOne({id:s.user_skill_id});if(!x||x.user_id!==req.userId)return res.status(403).json({error:'Forbidden.'});s.verification_status='unclear';s.ai_assessment='AI verification is unavailable.';await s.save();res.json({work_sample:clean(s),available:false});}

async function listCategories(req,res){const admin=req.user&&req.user.role==='admin';const wanted=req.query.status;if(wanted&&!admin)return res.status(403).json({error:'Admin access required.'});const q=admin&&wanted==='all'?{}:admin&&wanted?{status:wanted}:{status:'approved'};res.json({categories:(await Category.find(q).sort({name:1})).map(clean)});}
async function createCategory(req,res){if(!req.body.name)return res.status(400).json({errors:['name is required.']});try{const x=await Category.create({...req.body,status:'approved'});res.status(201).json({message:'Category created.',category:clean(x)});}catch(e){if(e.code===11000)return res.status(409).json({error:'Category already exists.'});throw e;}}
async function requestCategory(req,res){const name=String(req.body.name||'').trim();if(!name)return res.status(400).json({error:'name is required.'});const x=await Category.create({...req.body,name,status:'pending',requested_by_id:req.userId});res.status(201).json({message:'Category request submitted.',category:clean(x)});}
async function getCategory(req,res){const x=await byId(Category,req);if(!x||x.status!=='approved')return res.status(404).json({error:'Category not found.'});res.json({category:clean(x)});}
async function updateCategory(req,res){const x=await byId(Category,req);if(!x)return res.status(404).json({error:'Category not found.'});Object.assign(x,req.body);await x.save();res.json({message:'Category updated.',category:clean(x)});}
async function reviewCategory(req,res){const x=await byId(Category,req);if(!x)return res.status(404).json({error:'Category not found.'});if(x.status!=='pending')return res.status(400).json({error:'Only pending category requests can be approved.'});x.status=req.path.endsWith('/approve')?'approved':'rejected';x.rejection_reason=req.body.reason||null;await x.save();res.json({message:`Category ${x.status}.`,category:clean(x)});}
async function deleteCategory(req,res){const x=await byId(Category,req);if(!x)return res.status(404).json({error:'Category not found.'});await x.deleteOne();res.json({message:'Category deleted.'});}
const multipliers={colombo:1.3,gampaha:1.2,kandy:1.15,galle:1.1};
async function suggestedPrice(req,res){const category=String(req.query.category||''),scope=String(req.query.scope||''),qty=Number(req.query.quantity||1),district=String(req.query.district||'').toLowerCase();const rows=await PricingReference.find({category:new RegExp(`^${category.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i')}).sort({quantity:1});let price=null;if(rows.length){let row=rows.find(x=>x.scope.toLowerCase().includes(scope.toLowerCase())&&scope)||null;if(!row){if(qty<=rows[0].quantity)price=rows[0].base_price/rows[0].quantity*qty;else if(qty>=rows.at(-1).quantity)price=rows.at(-1).base_price/rows.at(-1).quantity*qty;else{const hi=rows.find(x=>x.quantity>=qty),lo=rows[rows.indexOf(hi)-1],t=(qty-lo.quantity)/(hi.quantity-lo.quantity),rate=lo.base_price/lo.quantity+t*(hi.base_price/hi.quantity-lo.base_price/lo.quantity);price=rate*qty;}}else price=row.base_price;price=Math.round(price*(multipliers[district]||1)/50)*50;}res.json({suggestedPrice:price});}
async function categoryPricing(req,res){const cat=await Category.findOne({id:Number(req.params.id)});if(!cat)return res.status(404).json({error:'Category not found.'});const location=String(req.query.location||''),row=await CategoryPricing.findOne({category_id:cat.id,location:new RegExp(`^${location}$`,'i')});const base=Number(cat.baseline_price||0),mult=multipliers[location.toLowerCase()]||1;res.json({category_id:cat.id,location,suggested_price:row?.average_price||Math.round(base*mult/50)*50,min_price:row?.min_price||null,max_price:row?.max_price||null,currency:'LKR'});}
async function seedPricing(req,res){const category_id=Number(req.params.id),cat=await Category.findOne({id:category_id});if(!cat)return res.status(404).json({error:'Category not found.'});const data={...req.body,category_id};const row=await CategoryPricing.findOneAndUpdate({category_id,location:data.location||''},{$set:data},{upsert:true,new:true,setDefaultsOnInsert:true});res.json({message:'Category pricing seeded.',pricing:clean(row)});}
async function seedDistrictPricing(req,res){const ids=req.params.id?[Number(req.params.id)]:(await Category.find({baseline_price:{$ne:null}})).map(x=>x.id);let seeded=0;for(const category_id of ids){const cat=await Category.findOne({id:category_id});if(!cat)continue;for(const [location,mult] of Object.entries(multipliers)){const avg=Math.round(Number(cat.baseline_price||0)*mult/50)*50;await CategoryPricing.findOneAndUpdate({category_id,location},{$set:{average_price:avg,min_price:Math.round(avg*.8/50)*50,max_price:Math.round(avg*1.2/50)*50,currency:'LKR'}},{upsert:true});seeded++;}}res.json({message:'District pricing seeded.',seeded});}

module.exports={stats,users,getUser,updateUser,deleteUser,deprecatedIdentity,otpUnavailable,listSkills,createSkill,getSkill,updateSkill,deleteSkill,listUserSkills,createUserSkill,getUserSkill,updateUserSkill,deleteUserSkill,samples,createSample,verifySample,listCategories,createCategory,requestCategory,getCategory,updateCategory,reviewCategory,deleteCategory,suggestedPrice,categoryPricing,seedPricing,seedDistrictPricing,isCommunityAdmin,clean};
