'use strict';
const {
  User, Skill, Community, CommunityMember, Job, CommunityApplication, Contract,
  ContractApplication, Conversation, Message, Notification, OpenCall, OpenCallSkill,
  Payment, Review, Report, AiReviewDigest, publicDoc,
} = require('../models');
const { isCommunityAdmin, clean } = require('./coreController');
const nowIso = value => value ? new Date(value).toISOString() : null;
const id = req => Number(req.params.id);
const wrap = fn => async (req,res,next) => { try { await fn(req,res); } catch(e) { next(e); } };
async function notify(userId,type,title,message,link_href=null){return Notification.create({user_id:userId,type,title,message,body:message,link_href});}
async function communityJson(c, detail=false){const out=clean(c);if(detail){out.admin=clean(await User.findOne({id:c.admin_id}));out.member_count=await CommunityMember.countDocuments({community_id:c.id,status:'approved'});}return out;}
async function jobJson(j, poster=false){const out=clean(j);const cat=await require('../models').Category.findOne({id:j.category_id});if(cat)out.category=clean(cat);if(poster)out.poster=clean(await User.findOne({id:j.posted_by_id}));out.application_count=await CommunityApplication.countDocuments({job_id:j.id});return out;}
async function applicationJson(a, extras=true){const out=clean(a);if(extras){out.community=await communityJson(await Community.findOne({id:a.community_id}));out.job=await jobJson(await Job.findOne({id:a.job_id}));}return out;}
async function contractJson(c){const out=clean(c);out.job=await jobJson(await Job.findOne({id:c.job_id}),true);out.community=await communityJson(await Community.findOne({id:c.community_id}));if(c.assigned_member_id)out.assigned_member=clean(await User.findOne({id:c.assigned_member_id}));out.payment=clean(await Payment.findOne({contract_id:c.id}));return out;}

const communities = {
 list:wrap(async(req,res)=>{const q={};if(req.query.status&&req.user?.role==='admin')q.status=req.query.status;else if(req.user?.role!=='admin')q.status='approved';res.json({communities:await Promise.all((await Community.find(q).sort({created_at:-1})).map(c=>communityJson(c,true)))});}),
 create:wrap(async(req,res)=>{const errors=[];for(const f of ['name','description','category_id','location'])if(!req.body[f])errors.push(`${f} is required.`);if(errors.length)return res.status(400).json({errors});const c=await Community.create({...req.body,admin_id:req.userId,status:'pending'});await CommunityMember.create({community_id:c.id,user_id:req.userId,role:'admin',status:'approved'});res.status(201).json({message:'Community created.',community:await communityJson(c,true)});}),
 get:wrap(async(req,res)=>{const c=await Community.findOne({id:id(req)});if(!c)return res.status(404).json({error:'Community not found.'});if(c.status!=='approved'&&req.user?.role!=='admin'&&req.userId!==c.admin_id)return res.status(404).json({error:'Community not found.'});res.json({community:await communityJson(c,true)});}),
 update:wrap(async(req,res)=>{const c=await Community.findOne({id:id(req)});if(!c)return res.status(404).json({error:'Community not found.'});Object.assign(c,req.body);await c.save();res.json({message:'Community updated.',community:await communityJson(c,true)});}),
 verify:wrap(async(req,res)=>{const c=await Community.findOne({id:id(req)});if(!c)return res.status(404).json({error:'Community not found.'});const status=req.body.verification_status||req.body.status;if(!['verified','rejected','approved'].includes(status))return res.status(400).json({errors:['verification_status is invalid.']});c.verification_status=status==='approved'?'verified':status;c.status=c.verification_status==='verified'?'approved':'rejected';c.verification_rejection_reason=req.body.reason||req.body.rejection_reason||null;await c.save();await notify(c.admin_id,'community_verification','Community verification updated',`Your community ${c.name} was ${c.verification_status}.`);res.json({message:'Community verification updated.',community:await communityJson(c,true)});}),
 remove:wrap(async(req,res)=>{const c=await Community.findOne({id:id(req)});if(!c)return res.status(404).json({error:'Community not found.'});if(c.admin_id!==req.userId)return res.status(403).json({error:'Forbidden.'});await Promise.all([CommunityMember.deleteMany({community_id:c.id}),OpenCall.deleteMany({community_id:c.id}),c.deleteOne()]);res.json({message:'Community deleted.'});}),
 digest:wrap(async(req,res)=>{const c=await Community.findOne({id:id(req)});if(!c)return res.status(404).json({error:'Community not found.'});const row=await AiReviewDigest.findOne({community_id:c.id});res.json({digest:row?.digest||{available:false,summary:null,positive_themes:[],improvement_themes:[]}});}),
};
const members={
 mine:wrap(async(req,res)=>{
  const rows=await CommunityMember.find({user_id:req.userId});
  const community_members=await Promise.all(rows.map(async membership=>({
   ...clean(membership),
   community:await communityJson(await Community.findOne({id:membership.community_id})),
  })));
  res.json({community_members});
 }),
 join:wrap(async(req,res)=>{const communityId=Number(req.params.community_id),c=await Community.findOne({id:communityId,status:'approved'});if(!c)return res.status(404).json({error:'Community not found.'});try{const m=await CommunityMember.create({community_id:communityId,user_id:req.userId,status:'pending',role:'member'});await notify(c.admin_id,'community_join_request','New join request',`${req.user.full_name} requested to join ${c.name}.`);res.status(201).json({message:'Join request submitted.',community_member:clean(m)});}catch(e){if(e.code===11000)return res.status(409).json({error:'You already have a membership or pending request for this community.'});throw e;}}),
 list:wrap(async(req,res)=>{const q={community_id:Number(req.params.community_id)};if(req.query.status)q.status=req.query.status;res.json({community_members:(await CommunityMember.find(q)).map(clean)});}),
 decide:wrap(async(req,res)=>{const m=await CommunityMember.findOne({id:id(req)});if(!m)return res.status(404).json({error:'Community member not found.'});if(!await isCommunityAdmin(req.userId,m.community_id))return res.status(403).json({error:'Community admin access required.'});m.status=req.path.endsWith('/approve')?'approved':'rejected';await m.save();res.json({message:`Membership ${m.status}.`,community_member:clean(m)});}),
 remove:wrap(async(req,res)=>{const m=await CommunityMember.findOne({id:id(req)});if(!m)return res.status(404).json({error:'Community member not found.'});if(!await isCommunityAdmin(req.userId,m.community_id))return res.status(403).json({error:'Community admin access required.'});await m.deleteOne();res.json({message:'Community member removed.'});}),
};
const jobs={
 list:wrap(async(req,res)=>{let q={posted_by_id:req.userId};if(req.user.role==='admin')q={};if(['1','true','yes'].includes(String(req.query.marketplace).toLowerCase()))q={status:'open'};if(req.query.category_id)q.category_id=Number(req.query.category_id);if(req.query.status)q.status=req.query.status;res.json({jobs:await Promise.all((await Job.find(q).sort({created_at:-1})).map(j=>jobJson(j,true)))});}),
 create:wrap(async(req,res)=>{for(const f of ['category_id','title','description','location','deadline','final_price'])if(!(f in req.body))return res.status(400).json({error:`Missing required field: ${f}`});if(!/^\d{4}-\d{2}-\d{2}$/.test(req.body.deadline))return res.status(400).json({error:'Invalid deadline format. Use YYYY-MM-DD.'});const j=await Job.create({...req.body,posted_by_id:req.userId,title:String(req.body.title).replace(/\b\w/g,c=>c.toUpperCase()),location:String(req.body.location).replace(/\b\w/g,c=>c.toUpperCase()),status:'open'});res.status(201).json({message:'Job created.',job:await jobJson(j)});}),
 get:wrap(async(req,res)=>{const j=await Job.findOne({id:id(req)});if(!j)return res.status(404).json({error:'Job not found.'});if(j.posted_by_id!==req.userId&&j.status!=='open'&&req.user.role!=='admin')return res.status(403).json({error:'Forbidden.'});res.json({job:await jobJson(j,true)});}),
 update:wrap(async(req,res)=>{const j=await Job.findOne({id:id(req)});if(!j)return res.status(404).json({error:'Job not found.'});if(j.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});if(j.status!=='open')return res.status(400).json({error:'Only open jobs can be updated.'});Object.assign(j,req.body);await j.save();res.json({message:'Job updated.',job:await jobJson(j)});}),
 remove:wrap(async(req,res)=>{const j=await Job.findOne({id:id(req)});if(!j)return res.status(404).json({error:'Job not found.'});if(j.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});if(j.status!=='open')return res.status(400).json({error:'Only open jobs can be deleted.'});await j.deleteOne();res.json({message:'Job deleted.'});}),
 applications:wrap(async(req,res)=>{const j=await Job.findOne({id:id(req)});if(!j)return res.status(404).json({error:'Job not found.'});if(j.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});res.json({applications:await Promise.all((await CommunityApplication.find({job_id:j.id}).sort({created_at:-1})).map(applicationJson))});}),
};
const communityApplications={
 mine:wrap(async(req,res)=>{const ids=(await Community.find({admin_id:req.userId})).map(x=>x.id);res.json({community_applications:await Promise.all((await CommunityApplication.find({community_id:{$in:ids}}).sort({created_at:-1})).map(applicationJson))});}),
 apply:wrap(async(req,res)=>{const job=await Job.findOne({id:Number(req.body.job_id)});if(!job)return res.status(404).json({error:'Job not found.'});if(job.status!=='open')return res.status(400).json({error:'Job is not open for applications.'});if(!await isCommunityAdmin(req.userId,req.body.community_id))return res.status(403).json({error:'Forbidden.'});if(req.body.proposed_cost==null||req.body.proposed_days==null)return res.status(400).json({errors:['proposed_cost and proposed_days are required.']});try{const a=await CommunityApplication.create({...req.body,job_id:job.id,community_id:Number(req.body.community_id),applied_by_id:req.userId,status:'applied',source:'applied'});res.status(201).json({message:'Application submitted.',community_application:await applicationJson(a)});}catch(e){if(e.code===11000)return res.status(409).json({error:'Community already applied to this job.'});throw e;}}),
 forJob:wrap(async(req,res)=>{const job=await Job.findOne({id:Number(req.params.job_id)});if(!job)return res.status(404).json({error:'Job not found.'});if(job.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});res.json({community_applications:await Promise.all((await CommunityApplication.find({job_id:job.id})).map(applicationJson))});}),
 decide:wrap(async(req,res)=>{const a=await CommunityApplication.findOne({id:id(req)});if(!a)return res.status(404).json({error:'Community application not found.'});if(a.status!=='applied')return res.status(400).json({error:'Application is no longer pending.'});const job=await Job.findOne({id:a.job_id});if(!job)return res.status(404).json({error:'Job not found.'});if(job.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});const approved=req.path.endsWith('/approve');a.status=approved?'approved':'rejected';await a.save();let contract=null;if(approved){const total=Number(a.proposed_cost||job.final_price),pct=Number(req.body.commission_percent||3);contract=await Contract.create({job_id:job.id,community_id:a.community_id,status:'pending_assignment',total_amount:total,agreed_price:total,commission_percent:pct,commission_amount:total*pct/100,member_payout:total-(total*pct/100)});job.status='assigned';await job.save();}res.json({message:approved?'Community application approved.':'Community application rejected.',community_application:clean(a),...(contract?{contract:await contractJson(contract)}:{})});}),
 invite:wrap(async(req,res)=>{const job=await Job.findOne({id:id(req)});if(!job)return res.status(404).json({error:'Job not found.'});if(job.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});const c=await Community.findOne({id:Number(req.body.community_id)});if(!c)return res.status(404).json({error:'Community not found.'});try{const a=await CommunityApplication.create({job_id:job.id,community_id:c.id,applied_by_id:req.userId,status:'applied',source:'invited',proposed_cost:Number(job.final_price),proposed_days:1});res.status(201).json({message:'Community invited.',community_application:await applicationJson(a)});}catch(e){if(e.code===11000)return res.status(409).json({error:'This community has already been invited to this job.'});throw e;}}),
};
module.exports={wrap,communities,members,jobs,communityApplications,contractJson,applicationJson,jobJson,communityJson,notify};
