'use strict';
const { User, Community, Job, Contract, Payment, Review, Report } = require('../models');
const { wrap, contractJson } = require('./domainController');
const { clean } = require('./coreController');
const TYPES=['user','employer','community'];
const REASONS=['fraud_or_scam','no_show_or_abandoned_job','harassment_or_abuse','fake_profile','unsafe_behavior','payment_dispute','inappropriate_content','other'];
const STATUSES=['open','under_review','resolved','dismissed'];
async function reportJson(r,admin=false){const out=clean(r);if(!admin)delete out.reporter_id;else{const u=await User.findOne({id:r.reporter_id});if(u)out.reporter={id:u.id,full_name:u.full_name,email:u.email,role:u.role};}return out;}
const reports={
 create:wrap(async(req,res)=>{const target_type=String(req.body.target_type||'').trim().toLowerCase(),reason=String(req.body.reason||'').trim().toLowerCase(),target_id=Number(req.body.target_id),errors=[];if(!TYPES.includes(target_type))errors.push('target_type must be user, employer, or community.');if(!REASONS.includes(reason))errors.push('reason is invalid.');let exists=false;if(target_type==='community')exists=Boolean(await Community.exists({id:target_id}));else{const u=await User.findOne({id:target_id});exists=Boolean(u&&(target_type==='user'||u.role==='employer'));}if(!target_id||!exists)errors.push('Target not found.');if(errors.length)return res.status(400).json({errors});const since=new Date(Date.now()-86400000);if(await Report.countDocuments({reporter_id:req.userId,created_at:{$gte:since}})>=5)return res.status(429).json({error:'Report submission limit reached. Try again later.'});if(await Report.exists({reporter_id:req.userId,target_type,target_id,reason,status:'open'}))return res.status(409).json({error:'You already have an open report for this target and reason.'});const r=await Report.create({reporter_id:req.userId,reporter_role:req.user.role,target_type,target_id,reason,description:String(req.body.description||'').trim()||null,evidence_url:req.evidenceUrl||null});res.status(201).json({message:'Report submitted.',report:await reportJson(r)});}),
 list:wrap(async(req,res)=>{const q={};for(const [field,allowed] of [['status',STATUSES],['target_type',TYPES],['reason',REASONS]])if(req.query[field]){if(!allowed.includes(req.query[field]))return res.status(400).json({errors:[`${field} is invalid.`]});q[field]=req.query[field];}const page=Math.max(1,Number(req.query.page||1)),per_page=Math.min(100,Math.max(1,Number(req.query.per_page||20)));if(!Number.isInteger(page)||!Number.isInteger(per_page))return res.status(400).json({errors:['page and per_page must be integers.']});const total=await Report.countDocuments(q),rows=await Report.find(q).sort({created_at:-1}).skip((page-1)*per_page).limit(per_page);res.json({reports:await Promise.all(rows.map(r=>reportJson(r,true))),pagination:{page,per_page,total,pages:Math.ceil(total/per_page)}});}),
 mine:wrap(async(req,res)=>{const page=Math.max(1,Number(req.query.page||1)),per_page=Math.min(100,Math.max(1,Number(req.query.per_page||20))),q={reporter_id:req.userId};const total=await Report.countDocuments(q),rows=await Report.find(q).sort({created_at:-1}).skip((page-1)*per_page).limit(per_page);res.json({reports:await Promise.all(rows.map(r=>reportJson(r))),pagination:{page,per_page,total,pages:Math.ceil(total/per_page)}});}),
 get:wrap(async(req,res)=>{const r=await Report.findOne({id:Number(req.params.id)});return r?res.json({report:await reportJson(r,true)}):res.status(404).json({error:'Report not found.'});}),
 update:wrap(async(req,res)=>{const r=await Report.findOne({id:Number(req.params.id)});if(!r)return res.status(404).json({error:'Report not found.'});if(req.body.status&&!STATUSES.includes(req.body.status))return res.status(400).json({errors:['status is invalid.']});if('status'in req.body)r.status=req.body.status;if('resolution_notes'in req.body)r.resolution_notes=req.body.resolution_notes;if(['resolved','dismissed'].includes(r.status)){r.resolved_by=req.userId;r.resolved_at=new Date();}await r.save();res.json({message:'Report updated.',report:await reportJson(r,true)});}),
};
const reviews={
 list:wrap(async(req,res)=>{const q={};if(req.query.community_id)q.community_id=Number(req.query.community_id);if(req.query.member_id)q.member_id=Number(req.query.member_id);res.json({reviews:(await Review.find(q)).map(clean)});}),
 create:wrap(async(req,res)=>{const errors=[];if(!req.body.contract_id)errors.push('contract_id is required.');if(!req.body.community_id)errors.push('community_id is required.');const rating=Number(req.body.rating);if(!Number.isInteger(rating)||rating<1||rating>5)errors.push('rating must be between 1 and 5.');if(errors.length)return res.status(400).json({errors});const c=await Contract.findOne({id:Number(req.body.contract_id)});if(!c)return res.status(404).json({error:'Contract not found.'});const j=await Job.findOne({id:c.job_id});if(!j||j.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});if(c.status!=='completed')return res.status(400).json({error:'Contract must be completed to leave a review.'});try{const r=await Review.create({...req.body,rating,reviewer_id:req.userId});const agg=await Review.aggregate([{$match:{community_id:Number(req.body.community_id)}},{$group:{_id:null,avg:{$avg:'$rating'}}}]);if(agg[0])await Community.updateOne({id:Number(req.body.community_id)},{$set:{reputation_score:agg[0].avg}});res.status(201).json({message:'Review created.',review:clean(r)});}catch(e){if(e.code===11000)return res.status(409).json({error:'Review already exists.'});throw e;}}),
};
const payments={
 list:wrap(async(req,res)=>{let rows;if(req.user.role==='admin')rows=await Payment.find();else{const contracts=await Contract.find({assigned_member_id:req.userId});const ownJobs=(await Job.find({posted_by_id:req.userId})).map(x=>x.id),ownCommunities=(await Community.find({admin_id:req.userId})).map(x=>x.id);const related=await Contract.find({$or:[{id:{$in:contracts.map(x=>x.id)}},{job_id:{$in:ownJobs}},{community_id:{$in:ownCommunities}}]});rows=await Payment.find({contract_id:{$in:related.map(x=>x.id)}});}res.json({payments:rows.map(clean)});}),
};
module.exports={reports,reviews,payments};
