'use strict';
const { User, Community, CommunityMember, Job, Contract, ContractApplication, Conversation, Message, Notification, Payment, Review, Report, OpenCall, OpenCallSkill, Skill, publicDoc } = require('../models');
const { wrap, contractJson, notify } = require('./domainController');
const { isCommunityAdmin, clean } = require('./coreController');
async function canAccess(userId,c){const j=await Job.findOne({id:c.job_id});return Boolean(j&&(j.posted_by_id===userId||c.assigned_member_id===userId||await isCommunityAdmin(userId,c.community_id)));}
const contracts={
 list:wrap(async(req,res)=>{let rows;if(req.user.role==='admin')rows=await Contract.find();else{const jobs=(await Job.find({posted_by_id:req.userId})).map(j=>j.id),communities=(await Community.find({admin_id:req.userId})).map(c=>c.id);rows=await Contract.find({$or:[{job_id:{$in:jobs}},{community_id:{$in:communities}},{assigned_member_id:req.userId}]});}res.json({contracts:await Promise.all(rows.map(contractJson))});}),
 attention:wrap(async(req,res)=>{let rows=await Contract.find({health_status:{$in:['at_risk','critical']}});if(req.user.role!=='admin'){const allowed=[];for(const c of rows)if(await canAccess(req.userId,c))allowed.push(c);rows=allowed;}res.json({contracts:await Promise.all(rows.map(contractJson))});}),
 get:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(req.user.role!=='admin'&&!await canAccess(req.userId,c))return res.status(403).json({error:'Forbidden.'});res.json({contract:await contractJson(c)});}),
 open:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(!await isCommunityAdmin(req.userId,c.community_id))return res.status(403).json({error:'Community admin access required.'});c.status='open_internally';await c.save();res.json({message:'Contract opened internally.',contract:await contractJson(c)});}),
 select:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(!await isCommunityAdmin(req.userId,c.community_id))return res.status(403).json({error:'Community admin access required.'});const a=await ContractApplication.findOne({id:Number(req.body.application_id),contract_id:c.id});if(!a)return res.status(404).json({error:'Contract application not found.'});a.status='approved';c.assigned_member_id=a.member_id;c.status='active';await Promise.all([a.save(),c.save(),ContractApplication.updateMany({contract_id:c.id,id:{$ne:a.id}},{$set:{status:'rejected'}})]);await notify(a.member_id,'contract_assigned','Contract assigned','You were selected for a contract.',`/contracts/${c.id}`);res.json({message:'Member selected.',contract:await contractJson(c)});}),
 selectMany:wrap(async(req,res)=>{const selections=Array.isArray(req.body.selections)?req.body.selections:[];if(!selections.length)return res.status(400).json({errors:['selections is required.']});req.body.application_id=selections[0].application_id;return contracts.select(req,res);}),
 submit:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(c.assigned_member_id!==req.userId)return res.status(403).json({error:'Forbidden.'});if(!req.body.deliverable_url&&!req.body.deliverable_notes)return res.status(400).json({errors:['deliverable_url or deliverable_notes is required.']});c.deliverable_url=req.body.deliverable_url||null;c.deliverable_notes=req.body.deliverable_notes||null;c.submitted_at=new Date();c.status='submitted';await c.save();res.json({message:'Deliverable submitted.',contract:await contractJson(c)});}),
 adminApprove:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(!await isCommunityAdmin(req.userId,c.community_id))return res.status(403).json({error:'Community admin access required.'});if(c.status!=='submitted')return res.status(400).json({error:'No submitted deliverable to approve.'});c.admin_approved_at=new Date();c.status='awaiting_poster_approval';await c.save();res.json({message:'Deliverable approved by community admin.',contract:await contractJson(c)});}),
 posterApprove:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)}),j=c&&await Job.findOne({id:c.job_id});if(!c)return res.status(404).json({error:'Contract not found.'});if(!j||j.posted_by_id!==req.userId)return res.status(403).json({error:'Forbidden.'});if(c.status!=='awaiting_poster_approval'&&!c.admin_approved_at)return res.status(400).json({error:'Deliverable must be approved by the community admin first.'});c.poster_approved_at=new Date();c.status='completed';j.status='closed';await Promise.all([c.save(),j.save()]);let p=await Payment.findOne({contract_id:c.id});if(!p){const total=Number(c.agreed_price||0),commission=total*Number(c.commission_percent||5)/100;p=await Payment.create({contract_id:c.id,total_amount:total,commission_amount:commission,member_payout:total-commission,status:'released',released_at:new Date()});}res.json({message:'Deliverable approved. Contract completed.',contract:await contractJson(c),payment:clean(p)});}),
};
const contractApplications={
 mine:wrap(async(req,res)=>res.json({contract_applications:(await ContractApplication.find({member_id:req.userId}).sort({created_at:-1})).map(clean)})),
 apply:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.body.contract_id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(c.status!=='open_internally')return res.status(400).json({error:'Contract is not open for applications.'});try{const a=await ContractApplication.create({...req.body,contract_id:c.id,member_id:req.userId,status:'pending'});res.status(201).json({message:'Contract application submitted.',contract_application:clean(a)});}catch(e){if(e.code===11000)return res.status(409).json({error:'You already applied to this contract.'});throw e;}}),
 list:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.contract_id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(!await isCommunityAdmin(req.userId,c.community_id))return res.status(403).json({error:'Forbidden.'});res.json({contract_applications:(await ContractApplication.find({contract_id:c.id})).map(clean)});}),
};
const messages={
 list:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(!await canAccess(req.userId,c))return res.status(403).json({error:'Forbidden.'});let conv=await Conversation.findOne({contract_id:c.id});if(!conv)conv=await Conversation.create({contract_id:c.id,created_by_id:req.userId});const rows=await Message.find({conversation_id:conv.id,deleted_for:{$ne:req.userId}}).sort({created_at:1});res.json({conversation:clean(conv),messages:rows.map(clean)});}),
 send:wrap(async(req,res)=>{const content=String(req.body.content||'').trim();if(!content)return res.status(400).json({errors:['content is required.']});const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.'});if(!await canAccess(req.userId,c))return res.status(403).json({error:'Forbidden.'});let conv=await Conversation.findOne({contract_id:c.id});if(!conv)conv=await Conversation.create({contract_id:c.id,created_by_id:req.userId});const m=await Message.create({conversation_id:conv.id,sender_id:req.userId,content});req.app.get('io')?.to(`conversation_${conv.id}`).emit('new_message',clean(m));res.status(201).json({message:clean(m)});}),
 suggest:wrap(async(req,res)=>{const c=await Contract.findOne({id:Number(req.params.id)});if(!c)return res.status(404).json({error:'Contract not found.',suggestion:null});if(!await canAccess(req.userId,c))return res.status(403).json({error:'Forbidden.',suggestion:null});const {askAi}=require('../services/aiService');const text=await askAi('Suggest one concise professional reply for this contract conversation. Return only the reply.',JSON.stringify((await Message.find({conversation_id:(await Conversation.findOne({contract_id:c.id}))?.id}).sort({created_at:-1}).limit(10)).reverse().map(m=>({sender_id:m.sender_id,content:m.content}))));return text?res.json({suggestion:text.replace(/^"|"$/g,''),available:true}):res.status(503).json({suggestion:null,available:false,error:'AI suggestion unavailable.'});}),
 deleteMine:wrap(async(req,res)=>{const m=await Message.findOne({id:Number(req.params.id)});if(!m)return res.status(404).json({error:'Message not found.'});if(m.deleted_for_everyone)return res.status(400).json({error:'Message was already deleted for everyone.'});if(!m.deleted_for.includes(req.userId))m.deleted_for.push(req.userId);await m.save();res.json({message:'Message deleted for you.'});}),
 deleteAll:wrap(async(req,res)=>{const m=await Message.findOne({id:Number(req.params.id)});if(!m)return res.status(404).json({error:'Message not found.'});if(m.sender_id!==req.userId)return res.status(403).json({error:'Only the sender can delete a message for everyone.'});m.deleted_for_everyone=true;m.deleted_at=new Date();m.content='This message was deleted.';await m.save();res.json({message:clean(m)});}),
};
const notifications={
 list:wrap(async(req,res)=>{const q={user_id:req.userId};if(req.query.unread==='1')q.read_at=null;const rows=await Notification.find(q).sort({created_at:-1}).limit(50);res.json({notifications:rows.map(clean),unread_count:await Notification.countDocuments({user_id:req.userId,read_at:null})});}),
 count:wrap(async(req,res)=>res.json({unread_count:await Notification.countDocuments({user_id:req.userId,read_at:null})})),
 read:wrap(async(req,res)=>{const n=await Notification.findOne({id:Number(req.params.id),user_id:req.userId});if(!n)return res.status(404).json({error:'Notification not found.'});if(!n.read_at){n.read_at=new Date();await n.save();}res.json({notification:clean(n)});}),
 all:wrap(async(req,res)=>{await Notification.updateMany({user_id:req.userId,read_at:null},{$set:{read_at:new Date()}});res.json({message:'All notifications marked read.'});}),
};
const openCalls={
 list:wrap(async(req,res)=>{
  const q=req.query.community_id?{community_id:Number(req.query.community_id)}:{};
  const rows=await OpenCall.find(q);
  const open_calls=await Promise.all(rows.map(async o=>{
   const links=await OpenCallSkill.find({open_call_id:o.id});
   const skills=await Promise.all(links.map(async x=>({...clean(x),skill:clean(await Skill.findOne({id:x.skill_id}))})));
   return {...clean(o),skills,required_skills:skills.map(x=>x.skill).filter(Boolean)};
  }));
  res.json({open_calls});
 }),
 create:wrap(async(req,res)=>{if(!req.body.community_id||!req.body.title)return res.status(400).json({errors:[...(!req.body.community_id?['community_id is required.']:[]),...(!req.body.title?['title is required.']:[])]});if(!await isCommunityAdmin(req.userId,req.body.community_id))return res.status(403).json({error:'Forbidden.'});const o=await OpenCall.create(req.body);for(const skill_id of req.body.skill_ids||[])await OpenCallSkill.create({open_call_id:o.id,skill_id});res.status(201).json({message:'Open call created.',open_call:clean(o)});}),
 get:wrap(async(req,res)=>{const o=await OpenCall.findOne({id:Number(req.params.id)});return o?res.json({open_call:clean(o)}):res.status(404).json({error:'Open call not found.'});}),
 update:wrap(async(req,res)=>{const o=await OpenCall.findOne({id:Number(req.params.id)});if(!o)return res.status(404).json({error:'Open call not found.'});if(!await isCommunityAdmin(req.userId,o.community_id))return res.status(403).json({error:'Forbidden.'});Object.assign(o,req.body);await o.save();if(req.body.skill_ids){await OpenCallSkill.deleteMany({open_call_id:o.id});for(const skill_id of req.body.skill_ids)await OpenCallSkill.create({open_call_id:o.id,skill_id});}res.json({message:'Open call updated.',open_call:clean(o)});}),
 remove:wrap(async(req,res)=>{const o=await OpenCall.findOne({id:Number(req.params.id)});if(!o)return res.status(404).json({error:'Open call not found.'});if(!await isCommunityAdmin(req.userId,o.community_id))return res.status(403).json({error:'Forbidden.'});await Promise.all([OpenCallSkill.deleteMany({open_call_id:o.id}),o.deleteOne()]);res.json({message:'Open call deleted.'});}),
};
module.exports={contracts,contractApplications,messages,notifications,openCalls};
